/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import javax.swing.JOptionPane;

/**
 *
 * @author akyla
 */
public class Transferir extends javax.swing.JFrame {
    Contas a = Contas.getInstancia();
    ContaEspecial b = ContaEspecial.getInstancia();
    ContaPoupanca c = ContaPoupanca.getInstancia();
    public Transferir() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        numeroA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        numeroB = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        transferir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tranferência");

        jLabel1.setText("Número da Conta Transferidora");

        numeroA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroAActionPerformed(evt);
            }
        });

        jLabel2.setText("Número da Conta na qual vai receber");

        numeroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numeroBActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Cancelar");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Valor a transferir");

        transferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroA)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(numeroB))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(transferir))
                        .addContainerGap(108, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1)
                        .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transferir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numeroB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void numeroAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroAActionPerformed

    private void numeroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numeroBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numeroBActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       //Testando numero da conta transferidora
        if(Integer.parseInt(numeroA.getText())== a.getNumero())
       {
                if(Integer.parseInt(numeroB.getText())== b.getNumero() )
                {
                    a.setSaldo(a.getSaldo()-Double.parseDouble(transferir.getText()));
                    b.setSaldo(b.getSaldo()+Double.parseDouble(transferir.getText()));
                    JOptionPane.showMessageDialog(null, "Transferência efetuado com sucesso!");
                    this.setVisible(false);
                    new Opções().setVisible(true);
                }
                if(Integer.parseInt(numeroB.getText())== c.getNumero())
                {
                    a.setSaldo(a.getSaldo()-Double.parseDouble(transferir.getText()));
                    c.setSaldo(c.getSaldo()+Double.parseDouble(transferir.getText()));
                    JOptionPane.showMessageDialog(null, "Transferência efetuado com sucesso!");
                    this.setVisible(false);
                    new Opções().setVisible(true);
                }
       }
        if(Integer.parseInt(numeroA.getText())== b.getNumero())
        {
                if(Integer.parseInt(numeroB.getText())== a.getNumero() )
                {
                    b.setSaldo(b.getSaldo()-Double.parseDouble(transferir.getText()));
                    a.setSaldo(a.getSaldo()+Double.parseDouble(transferir.getText()));
                    JOptionPane.showMessageDialog(null, "Transferência efetuado com sucesso!");
                    this.setVisible(false);
                    new Opções().setVisible(true);
                }
                if(Integer.parseInt(numeroB.getText())== c.getNumero() )
                {
                    a.setSaldo(a.getSaldo()-Double.parseDouble(transferir.getText()));
                    c.setSaldo(c.getSaldo()+Double.parseDouble(transferir.getText()));
                    JOptionPane.showMessageDialog(null, "Transferência efetuado com sucesso!");
                    this.setVisible(false);
                    new Opções().setVisible(true);
                }
              
        }
        if(Integer.parseInt(numeroA.getText())== c.getNumero())
        {
                if(Integer.parseInt(numeroB.getText())== b.getNumero() )
                {
                    c.setSaldo(c.getSaldo()-Double.parseDouble(transferir.getText()));
                    b.setSaldo(b.getSaldo()+Double.parseDouble(transferir.getText()));
                    JOptionPane.showMessageDialog(null, "Transferência efetuado com sucesso!");
                    this.setVisible(false);
                    new Opções().setVisible(true);
                }
                if(Integer.parseInt(numeroB.getText())== a.getNumero() )
                {
                    c.setSaldo(c.getSaldo()-Double.parseDouble(transferir.getText()));
                    a.setSaldo(a.getSaldo()+Double.parseDouble(transferir.getText()));
                    JOptionPane.showMessageDialog(null, "Transferência efetuado com sucesso!");
                    this.setVisible(false);
                    new Opções().setVisible(true);
                }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    this.setVisible(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void transferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transferirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transferir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transferir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextField numeroA;
    private javax.swing.JTextField numeroB;
    private javax.swing.JTextField transferir;
    // End of variables declaration//GEN-END:variables
}
